export class Configure {
  host = "http://localhost:4000"
  urlLogin = this.host + "/auth/login"
  urlCreateAccount = this.host + "/admin/account/create"
  urlListAccount = this.host + "/admin/account/get-list"
  urlUpdateAccount = this.host + "/admin/account/update/"
  urlGetAccountById = this.host + "/admin/account/"
  urlDeleteAccountById = this.host + "/admin/account/delete/"
  urlChangeLockAccountById = this.host + "/admin/account/changeLock/"
  urlCreateGroupQuestion = this.host + "/group-question/create"
  urlListPart = this.host + "/part/get-list"
  urlListTest = this.host + "/tests"
  urlCreateTest = this.host + "/tests/create"
  urlUpdateTestById = this.host + "/"
  urlDeleteTestById = this.host + "/"
}